import Head from 'next/head';
import About from '../components/About/About';
import Header from '../components/common/Header';
import Hero from '../components/Hero/Hero';
import WorkExperiences from '../components/Experiences/WorkExperiences';
import Skills from '../components/Skills/Skills';
import Projects from '../components/Projects/Projects';
import Contact from '../components/Contact/Contact';
import Link from 'next/link';
import { ChevronDoubleUpIcon } from '@heroicons/react/solid';
import { Experience, PageInfo, Project, Skill, Social } from '../typings';
import { fetchPageInfo } from '../utils/fetchPageInfo';
import { fetchExperiences } from '../utils/fetchExperiences';
import { fetchSkills } from '../utils/fetchSkills';
import { fetchProjects } from '../utils/fetchProjects';
import { fetchSocials } from '../utils/fetchSocials';
import { ToastContextProvider } from '../context/ToastContext';

type Props = {
  pageInfo: PageInfo;
  experiences: Experience[];
  skills: Skill[];
  projects: Project[];
  socials: Social[];
};

const Home = ({ pageInfo, experiences, skills, projects, socials }: Props) => {
  const {
    cv: { cvUrl },
  } = pageInfo || {};

  return (
    <div className="bg-[rgb(36,36,36)] text-white h-screen overflow-y-auto overflow-x-hidden snap-y snap-proximity sm:snap-mandatory z-0 scrollbar-thin scrollbar-track-gray-400/20 scrollbar-thumb-violet-500 ">
      <Head>
        <title>Jonathan Surle - Dev Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ToastContextProvider>
        {/* Header */}
        <Header socials={socials} cv={cvUrl} />

        {/* Hero */}
        <section id="hero" className="snap-start">
          <Hero pageInfo={pageInfo} />
        </section>

        {/* About */}
        <section id="about" className="snap-start">
          <About pageInfo={pageInfo} />
        </section>

        {/* Skills */}
        <section id="skills" className="snap-start">
          <Skills skills={skills} />
        </section>

        {/* Experience */}
        <section id="experiences" className="snap-start">
          <WorkExperiences experiences={experiences} />
        </section>

        {/* Projects */}
        <section id="projects" className="snap-start">
          <Projects projects={projects} />
        </section>

        {/* Contact Me */}
        <section id="contact" className="snap-end">
          <Contact />
        </section>

        <footer className="sticky bottom-16 md:bottom-5 flex md:justify-center">
          <Link href="#hero">
            <ChevronDoubleUpIcon className="h-10 w-10 animate-pulse hover:animate-bounce" />
          </Link>
        </footer>
      </ToastContextProvider>
    </div>
  );
};

export default Home;

export const getStaticProps = async () => {
  const pageInfo = await fetchPageInfo();
  const experiences = await fetchExperiences();
  const skills = await fetchSkills();
  const projects = await fetchProjects();
  const socials = await fetchSocials();

  return {
    props: { pageInfo, experiences, skills, projects, socials },
    revalidate: 10,
  };
};
